use submodule dependencies to build the project
libocca/occa-transpiler pull request #178
Opened 2024-04-15 15:35 UTC by vyast-softserveinc

Description: make the project building from submodules by the request
(Google Tests library is not included)

2024-04-16 11:00 UTC, IuriiKobein approved these changes

2024-04-17 08:50 UTC, kchabSS requested changes
Please rename `submodules` to `deps`or similar.

2024-04-17 08:50 UTC, kchabSS commented on .gitmodules
> +	path = submodules/expected
Usually, the folder is named `deps` or `dependecy` or `3rdparty`.
`Submodule` can be some extension, but the name does not sound like some a 3rd party dependency.

2024-04-17 21:55 UTC, IuriiKobein reviewed
Please update readme.md accordingly.

2024-04-19 10:03 UTC, kchabSS approved these changes

2024-04-19 11:06 UTC, IuriiKobein approved these changes

2024-04-22 09:06 UTC, merged